config/routes.rb
Rails.application.routes.draw do
  get 'blog/index'

  get 'blog/show'

  get 'blog/new'

  get 'blog/edit'

  get 'post/index'

  get 'post/show'

  get 'post/new'

  get 'post/edit'

  resources :posts
  resources :blogs do
    resources :posts
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:blog_title)
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
 # find the blog for the id provided
 @blog = Blog.find(params[:blog_id])
 # Get all the posts associated with this blog
 @posts = @blog.posts
 end
 # GET /blogs/1/posts/2
 def show
 @blog = Blog.find(params[:blog_id])
 # Find an post in blogs 1 that has id=2
 @post = @blog.posts.find(params[:id])
 end
 # GET /blogs/1/posts/new
 def new
 @blog = Blog.find(params[:blog_id])
 # Associate an post object with the blog
 @post = @blog.posts.build
 end
 # POST /blogs/1/posts
 def create
 @blog = Blog.find(params[:blog_id])

 @post = @blog.posts.build(posts_params)
 if @post.save
 # Post saved, redirect to blog page
 redirect_to blog_post_url(@blog, @post)
 else
 render :action => "new"
 end
 end
 # GET /blogs/1/posts/2/edit
 def edit
 @blog = Blog.find(params[:blog_id])
 @post = @blog.posts.find(params[:id])
 end
 # PUT /blogs/1/posts/2
 def update
 @blog = Blog.find(params[:blog_id])
 @post = Post.find(params[:id])
 if @post.update_attributes(posts_params)
 # Post saved, redirect
 redirect_to blog_post_url(@blog, @post)
 else
 render :action => "edit"
 end
 end
 # DELETE /blogs/1/posts/2
 def destroy
 @blog = Blog.find(params[:blog_id])
 @post = Post.find(params[:id])
 @post.destroy
 respond_to do |format|
 format.html { redirect_to blog_posts_path(@blog) }
 format.xml { head :ok }
 end
 end

 def set_post
   @post = Post.find(params[:id])
 end

 def posts_params
params.require(:post).permit(:post_message)
 end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/edit.html.erb
<h1>Blog#edit</h1>
<p>Find me in app/views/blog/edit.html.erb</p>

app/views/blog/index.html.erb
<h1>Blog#index</h1>
<p>Find me in app/views/blog/index.html.erb</p>

app/views/blog/new.html.erb
<h1>Blog#new</h1>
<p>Find me in app/views/blog/new.html.erb</p>

app/views/blog/show.html.erb
<p>
 <b>Blog Title:</b>
 <%= @blog.blog_title %>
</p>
<!-- Display posts of a blog -->
<h2>Posts</h2>
<% @blog.posts.each do |post| %>
 <p>
 <b>Message:</b>
 <%= post.post_message %>
 </p>
<% end %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %> |
<%= link_to 'Show Posts', blog_posts_path(@blog) %>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blog_title %><br>
    <%= f.text_field :blog_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blog</h1>

<table>
  <thead>
    <tr>
      <th>Blog title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.blog_title %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
 <b>Blog Title:</b>
 <%= @blog.blog_title %>
</p>
<!-- Display posts of a blog -->
<h2>Posts</h2>
<% @blog.posts.each do |post| %>
 <p>
 <b>Message:</b>
 <%= post.post_message %>
 </p>
<% end %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %> |
<%= link_to 'Show Posts', blog_posts_path(@blog) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogSca</title>
  <h1>Whattt????.</h1>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post/edit.html.erb
<h1>Post#edit</h1>
<p>Find me in app/views/post/edit.html.erb</p>

app/views/post/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>

app/views/post/new.html.erb
<h1>Post#new</h1>
<p>Find me in app/views/post/new.html.erb</p>

app/views/post/show.html.erb
<h1>Post#show</h1>
<p>Find me in app/views/post/show.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for([@blog, @post]) do |f| %>
 <% if @post.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(@post.errors.count, "error") %> prohibited this blog from being saved:</h2>
 <ul>
 <% @post.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <div class="field">
 <p>
 <%= f.label :post_message %><br />
 <%= f.text_area :post_message %>
 </p>
 </div>
 <div class="actions">
 <%= f.submit %>
 </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= render 'form' %>
<%= link_to 'Show', blog_post_path(@blog, @post) %> |
<%= link_to 'Back', blog_posts_path(@blog) %>

app/views/posts/index.html.erb
<h1>Posts in <%= @blog.blog_title %></h1>
<table>
<% for post in @posts %>
 <tr>
 <td><%= post.post_message %></td>
 <td><%= link_to 'Show', blog_post_path(@blog, post) %></td>
 <td><%= link_to 'Edit', edit_blog_post_path(@blog, post) %></td>
 <td><%= link_to 'Destroy', blog_post_path(@blog, post), :confirm =>
'Are you sure?', :method => :delete %></td>
 </tr>
<% end %>
</table>
<br />
<%= link_to 'New Post', new_blog_post_path(@blog) %>
<%= link_to 'Back to Blog', @blog %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to 'Back', blog_posts_path(@blog) %>

app/views/posts/show.html.erb
<h1>Post in <%= @blog.blog_title %></h1>
<p>
 <%= @post.post_message %>
</p>
<%= link_to 'Edit', edit_blog_post_path(@blog, @post) %> |
<%= link_to 'Back', blog_posts_path(@blog) %>